pltsDir = $(wildcard plt*/)
PDF = $(patsubst %/,%.pdf,$(pltsDir))
PNG = $(patsubst %/,%.png,$(pltsDir))

pdf: $(PDF)

png: $(PNG)

%.pdf: %/
	castro_yt_plot.py -f $< -a -t pdf

%.png: %/
	castro_yt_plot.py -f $< -a -t png

# remove the pdf / png output generated by this makefile
clean:
	find . \( -iname '*.pdf' -o -iname '*.png' \) -exec rm {} +

# remove the chk and plt folders generated by Castro
Clean:
	find . \( -iname 'plt*' -o -iname 'chk*' \) -type d -exec rm -r {} +
